### ISSUE TITLE
Not clear how to login with Trigger.dev template

### ISSUE THREAD

**Issue by maelp** [Dokploy/templates#106]
When running the trigger.dev template it seems we need to get a "magic link" through email, but since there is no mail server config it doesn't work, how are we supposed to login?

**Comment by maelp** [comment]
After checking the doc you have to go to the log console, but it would perhaps be better to have some kind of documentation for this (see https://github.com/Dokploy/templates/issues/107)

![Image](https://github.com/user-attachments/assets/ead08fff-5cc4-4413-85a9-3c5b7649c143)

**Comment by maelp** [comment]
Although even this doesn't seem to work (at least with the "basic" setup)... using the magic link from the log console just redirects back to the login page

**Comment by maelp** [comment]
Added it here
```yml
  electric:
    image: electricsql/electric:${ELECTRIC_IMAGE_TAG:-latest}
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      DATABASE_URL: ${DATABASE_URL}?sslmode=disable
      ELECTRIC_SECRET: ${ELECTRIC_SECRET}
    networks:
      - webapp
    depends_on:
      - postgres
    ports:
      - 3000
```
