### ISSUE TITLE
WordPress Template : REST API and Loopback Requests Failing due to cURL timeout (Error 28)

### ISSUE THREAD

**Issue by thepiyushchandwani** [Dokploy/templates#128]
### To Reproduce

1. Deploy a WordPress site using the default WordPress Install Template on Dokploy.
2. Complete the deployment without modifying any isolation or network settings.
3. Visit WordPress Admin → Tools → Site Health.

You will find two major errors :
  - REST API is not working :
    (http_request_failed) cURL error 28: Connection timed out after 10000 milliseconds
  
  - Loopback request failed :
     cURL error 28: Connection timed out after 10000 milliseconds

### Current vs. Expected behavior

Current Behavior:
After following the steps above, REST API endpoints fail to respond, and loopback requests timeout, breaking several WordPress features such as the Block Editor, scheduled cron jobs, and plugin/theme management.

Expected Behavior:
REST API endpoints and loopback requests should work immediately after a clean deployment without manual intervention, ensuring full functionality of WordPress.

![Image](https://github.com/user-attachments/assets/75cdbebf-8f65-469d-9484-a3efa73634e2)

### Provide environment information

```bash
Operating System : Ubuntu 24.04.2 LTS x86_64
Dokploy : v0.21.8
What application are you trying to deploy : Wordpress
```

### Which area(s) are affected? (Select all that apply)

Docker Compose, Traefik, Application

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

The site is accessible, but internal cURL requests fail, which seems related to networking setup in the template.

### Will you send a PR to fix it?

No

**Comment by thepiyushchandwani** [comment]
> [@Siumauricio](https://github.com/Siumauricio)
> 
> I don't think this is strictly a template issue. I am using a raw compose with my own custom WP image, and I am now seeing this issue in WP Health Check on deployments.
> 
> Raw Compose - network isolated deployment Health check now shows it cannot complete loopback or rest api requests. I don't recall this ever showing during any prev tests.
> 
> Were any updates released that could be breaking something here?
> 
> I'll keep digging into it for a bit.

@Siumauricio ,

After some digging, I found a solution that worked for my setup.

##  Problem

WordPress couldn't properly talk to itself using its public domain from inside the container. This caused issues like:
- Failed health checks
- Internal loopback timeouts

##  Solution

### 1. Set correct WordPress URLs in docker-compose.yml

Make sure the WordPress container knows its actual public URL:

```yaml
services:
  wordpress:
    environment:
      WP_HOME: https://yourdomain.com       # Replace with your real domain
      WP_SITEURL: https://yourdomain.com    # Replace with your real domain
```

### 2. Add extra_hosts to handle internal loopback

This was the key part.

#### a. Find your Traefik container's internal IP on the shared Docker network

Run:

```bash
docker inspect <traefik_container_name_or_id>
```

Then look for something like:

```json
"Networks" -> "<your_shared_network>" -> "IPAddress"
```

**Example:**
```
10.0.1.48 on the dokploy-network
```

#### b. Add extra_hosts to your WordPress service

Tell your WordPress container that requests to its public domain should route to Traefik's internal IP.

Here's how your `docker-compose.yml` would look:

```yaml
services:
  wordpress:
    image: wordpress
    environment:
      WP_HOME: https://yourdomain.com
      WP_SITEURL: https://yourdomain.com
    volumes:
      - ./wp-data:/var/www/html
    networks:
      - dokploy-network     # Replace with your shared network name
    extra_hosts:
      - "yourdomain.com:10.0.1.48"  # Use the Traefik IP you found
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress.rule=Host(`yourdomain.com`)"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
        - "traefik.docker.network=dokploy-network"
```

### Example Configuration

In my case, the working line looked like this:

```yaml
extra_hosts:
  - "wp.domain.com:10.0.1.48"
```

##  Why This Works

When WordPress performs internal actions like cron jobs or health checks, it tries to connect to `https://yourdomain.com`.

**Without extra_hosts:** WordPress may try to go out to the public internet and route back in. This could be:
- Blocked by firewalls
- Completely fail (especially with no internet access)

**With extra_hosts:** You force WordPress to resolve the domain to an internal IP (your Traefik container), making the request stay inside the Docker network.

### How It Works

1. WordPress sends a request to `https://yourdomain.com`
2. DNS resolves it to `10.0.1.48` (Traefik's internal IP)
3. Traefik sees it's for `yourdomain.com`, and forwards it right back to the WordPress container

This keeps everything local, fast, and reliable.
