### ISSUE TITLE
Templates are not working out of the box: 404 not found

### ISSUE THREAD

**Issue by bst27** [Dokploy/templates#190]
### To Reproduce

1. Create a project and then select "Create Service" -> "Template"
2. Select "Uptime Kuma" template
3. Open the created service and click "deploy" to start the service
4. Open the "Domains" tab and click on the URL to open the service website
5. You will ge a 404 not found error

### Current vs. Expected behavior

I noticed that the provider raw template shows the following:
```
version: "3.8"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    restart: always
    volumes:
      - uptime-kuma-data:/app/data

volumes:
  uptime-kuma-data:
```

So for my understanding this is missing the connection to the dokploy network as described there:
[Docker Compose with Dokploy](https://docs.dokploy.com/docs/core/docker-compose/example)

So if I change the template code as follows before deploying it works immediately:
```
version: "3.8"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    restart: always
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - dokploy-network

volumes:
  uptime-kuma-data:

networks:
  dokploy-network:
    external: true
```

But shouldn't this work out of the box when selecting a template? At least that is what I was expecting as a new user which used a template to try things out.

### Provide environment information

```bash
Dokploy version: v0.22.7
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

Maybe, need help
