### ISSUE TITLE
Add template for Backrest

### ISSUE THREAD

**Issue by maelp** [Dokploy/templates#34]
### What problem will this feature address?

Basic template for backup service Backrest to add to the app templates

```
version: "3.8"

services:
  backrest:
    image: garethgeorge/backrest:v1.7.3
    container_name: backrest
    hostname: backrest
    restart: unless-stopped
    ports:
      - "9898:9898"
    environment:
      - BACKREST_PORT=9898
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/data/backrest/data:/data
      - /mnt/data/backrest/config:/config
      - /opt/backrest/cache:/cache
      - /mnt/data:/userdata:ro # we mount /mnt/data (or whatever folder you want) to /userdata (that we want to backup)
```

### Describe the solution you'd like

Add a template

### Describe alternatives you've considered

Do it manually

### Additional context

Could be interesting to have default backups for Docker volumes and/or a `/mnt/data` disk for dokploy (this is where I store all the data for my containers, I find it "safer" than docker volumes which are a bit less easy to look at and manage)

### Will you send a PR to implement it?

Maybe, need help
