### ISSUE TITLE
Add template for ownCloud infinitescale

### ISSUE THREAD

**Issue by maelp** [Dokploy/templates#37]
```yaml
version: "3.7"

# Check https://fariszr.com/owncloud-infinite-scale-docker-setup/
services:
  ocis:
    image: owncloud/ocis:7.1.1
    user: 0:0
    ports:
      - 127.0.0.1:9200:9200
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      OCIS_URL: "https://ocis.xn--l3haa.st"
      OCIS_LOG_LEVEL: info
      PROXY_TLS: false
      OCIS_INSECURE: true
      IDM_ADMIN_PASSWORD: ${IDM_ADMIN_PASSWORD}
      SETTINGS_GRPC_ADDR: 0.0.0.0:9191
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142 # make the REVA gateway accessible to the app drivers
      # PROXY_TLS is set to "false", the download url has no https
      STORAGE_USERS_DATA_GATEWAY_URL: http://ocis:9200/data
      THUMBNAILS_FILESYSTEMSTORAGE_ROOT: /var/lib/ocis-thumbnails
    volumes:
      - owncloud-ocis/ocis.yaml:/etc/ocis/ocis.yaml
      - owncloud-ocis/data:/var/lib/ocis
      - owncloud-ocis/thumbnails:/var/lib/ocis-thumbnails
```

and

```
IDM_ADMIN_PASSWORD: somePaswordForAdmin
```
