### ISSUE TITLE
[Bug]: Maybe Finance Template is bug with the lastest version "0.4.3"

### ISSUE THREAD

**Issue by louanfontenele** [Dokploy/templates#60]
docker-composer.yml
```yml
services:
  app:
    image: ghcr.io/maybe-finance/maybe:latest
    restart: unless-stopped
    volumes:
      - ../files/uploads:/app/uploads
    environment:
      DATABASE_URL: postgresql://maybe:maybe@db:5432/maybe
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SELF_HOSTED: true
      SYNTH_API_KEY: ${SYNTH_API_KEY}
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      GOOD_JOB_EXECUTION_MODE: async
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maybe
      POSTGRES_USER: maybe
      POSTGRES_PASSWORD: maybe

volumes:
  db-data:
```

---

Logs:
[maybe-finance-maybe-hsfldq-app-1-20250403_175134.log.txt](https://github.com/user-attachments/files/19592236/maybe-finance-maybe-hsfldq-app-1-20250403_175134.log.txt)

[maybe-finance-maybe-hsfldq-db-1-20250403_175129.log.txt](https://github.com/user-attachments/files/19592235/maybe-finance-maybe-hsfldq-db-1-20250403_175129.log.txt)

---

When I try to do something, the website crashes for a few seconds, and back online again.
