### ISSUE TITLE
Add Jellyfin-Vue to Jellyfin

### ISSUE THREAD

**Issue by maelp** [Dokploy/templates#87]
It's a better view! https://github.com/jellyfin/jellyfin-vue

Should be as easy as 

```
  jellyfin_vue:
    container_name: jellyfin_vue
    image: ghcr.io/jellyfin/jellyfin-vue:unstable
    restart: always
    ports:
      - 8080:80
```
